/* COPYRIGHT (C) HARRY CLARK 2024 */

/* SEGA MEGA DRIVE CHECKSUM TOOLKIT */

/* THIS FILE PERTAINS TOWARDS THE MODULARISATION OF */
/* COMPONENTS SURROUDNING THE CHECKSUM AND THEIR RELEVANT ARGS */

/* NESTED INCLUDES */

#include "common.h"
#include "util.h"

CHECKSUM CHECKSUM_ARGS;

/* COMPUTE THE CHECKSUM BY DETERMINING THE SOURCE OF THE FILE */
/* THE ORIGIN IN WHICH THE OFFSET HEX VALUE EXISTS INSIDE OF
/* THE BINARY OFFSET RELATIVE TO THE HANDLE */

int COMPUTE_CHECKSUM()
{
    fseek(CHECKSUM_ARGS.OPEN_FILE, CHECK_START_OFFSET, SEEK_SET);
    while (fread(&CHECKSUM_ARGS.LENGTH, sizeof(CHECKSUM_ARGS.LENGTH), 1, CHECKSUM_ARGS.OPEN_FILE))
    {
        CHECKSUM_ARGS.COMPUTE += CHECKSUM_ARGS.LENGTH;
    }

    CHECKSUM_ARGS.COMPUTE &= CHECK_MASK;
    return 0;
}

/* FIX THE CHECKSUM ASSUMING THAT THE READER OFFSET IS OUT OF PLACE */
/* OR IF THE CURRENT CHECKSUM OF THE ROM DUMP DOESN'T MATCH */

void FIX_CHECKSUM(void)
{
    fseek(CHECKSUM_ARGS.OPEN_FILE, CHECK_HANDLE_OFFSET, SEEK_SET);
    fwrite((&CHECKSUM_ARGS.COMPUTE), sizeof(CHECKSUM_ARGS.COMPUTE), 1, CHECKSUM_ARGS.OPEN_FILE);
}

/* A FUNCTION TO MODULARISE THE CODE TO MAKE MAIN NOT AS CLUTTERED */
/* THIS IS FOR PRINTING THE FINAL AND FIXED CHECKSUM */

void PRINT_CHECKSUM(void)
{
    if(CHECKSUM_ARGS.READ == CHECKSUM_ARGS.COMPUTE)
        printf("Checksum Correct\n");
    else
        FIX_CHECKSUM();
        printf("Checksum Fixed\n");
}

/* CHECKS TO SEE IF THE CORRESPONDING FILE PROVIDED */
/* IS A VALID MEGA DRIVE/GENESIS ROM */

int IS_VALID_ROM()
{
    fseek(CHECKSUM_ARGS.OPEN_FILE, CHECK_INIT, SEEK_SET);

    if(fread(&CHECKSUM_ARGS, sizeof(CHECKSUM_ARGS), 1, CHECKSUM_ARGS.OPEN_FILE) != 1)
    {
        printf("Error reading ROM Header, possible corrupted ROM, %x");
        return EXIT_FAILURE;
    }

    if(memcmp(CHECKSUM_ARGS.SIGNATURE, "SEGA", 4) == 0)
    {
        return 1;
    }

    return 0;    
}