/* Copyright (C) 2023 Harry Clark */

/* SEGA Mega Drive Checksum Tool */

/* THIS FILE REFERS TO THE MAIN FUNCTIONALITY OF THE PROGRAM */

/* NESTED INCLUDES */

#include "util.h"

/* COMPUTE THE CHECKSUM BY DETERMING THE SOURCE OF THE FILE */
/* THE ORIGIN IN WHICH THE OFFSET HEX VALUE EXISTS INSIDE OF 
/* THE BINARY OFFSET RELATIVE TO THE HANDLE */

/* THE CHECKSUM IS DETERMINED BY THE VECTOR TABLE OF THE M68K */
/* TO DETERMINE IF ANY IRQ'S HAVE TO BE CALLED TO DETECT */
/* ILLEGAL OPERATIONS OR AN INACCESSIBLE CHUNK OF MEMORY */

#ifdef USE_HEX_ARGS

static CHECKSUM::COMPUTE* COMPUTE_CHECKSUM(CHECKSUM::OPEN_FILE* OF)
{
	fseek(OF, CHECK_START_OFFSET, CHECK_HANDLE_OFFSET);
}

#undef BIT_ARGS

static inline BIT::BYTE_TO_INT* BYTE_TO_INT(CHECKSUM::OPEN_FILE* OF)
{
	return fgetc(OF);
}

static inline BIT::WORD_TO_INT* WORD_TO_INT(CHECKSUM::OPEN_FILE* OF)
{
	BIT_HI = BYTE_TO_INT(OF) << 8;
	BIT_LO = BYTE_TO_INT(OF);
	return BIT_SUM;
}

#endif


int main(int argc, char** argv)
{
	COMPUTE_CHECKSUM();
	BYTE_TO_INT();
	WORD_TO_INT();
	return 0;
}
