/* Copyright (C) 2023 Harry Clark */

/* SEGA Mega Drive Checksum Tool */

/* THIS FILE REFERS TO THE MAIN FUNCTIONALITY OF THE PROGRAM */

/* NESTED INCLUDES */

#include "util.h"

/* COMPUTE THE CHECKSUM BY DETERMING THE SOURCE OF THE FILE */
/* THE ORIGIN IN WHICH THE OFFSET HEX VALUE EXISTS INSIDE OF 
/* THE BINARY OFFSET RELATIVE TO THE HANDLE */

/* THE CHECKSUM IS DETERMINED BY THE VECTOR TABLE OF THE M68K */
/* TO DETERMINE IF ANY IRQ'S HAVE TO BE CALLED TO DETECT */
/* ILLEGAL OPERATIONS OR AN INACCESSIBLE CHUNK OF MEMORY */

#ifdef USE_HEX_ARGS

static CHECKSUM::COMPUTE* COMPUTE_CHECKSUM(CHECKSUM::OPEN_FILE* OF)
{
	fseek(OF, CHECK_START_OFFSET, CHECK_HANDLE_OFFSET);
}

#undef BIT_ARGS

/* ACCESS THE FILES CONTENTS AND CONVERT THOSE BYTEWISE VALUES TO INTS */
/* READY TO BE PARSED */

/* I CONVERT THE BYTES INTO INTS TO BE ABLE TO BE ABLE TO COMMUNICATE */
/* WITH THE CARTRIDGE'S VECTOR TABLE */

/* SEE M68K VECTOR TABLE: https://wiki.neogeodev.org/index.php?title=68k_vector_table */


static inline BIT::BYTE_TO_INT* BYTE_TO_INT(CHECKSUM::OPEN_FILE* OF)
{
	return fgetc(OF);
}

/* IN ACCORDANCE WITH THE STATUS REGISTER ON THE M68K, THIS ALLOWS THE CARTRIDGE */
/* TO COMMUNICATE WITH THE CONDITION CODES */

/* TAKING INTO ACCOUNT MSB/LSB, WE DETERMINE THE HIGH AND LOW ORDER OF */
/* THE BYTE ORIENTATION TO EQUATE 16 BITS (1 WORD) */

/* SEE FIGURE 2-5: https://www.nxp.com/docs/en/reference-manual/MC68000UM.pdf#page=21 */

static inline BIT::WORD_TO_INT* WORD_TO_INT(CHECKSUM::OPEN_FILE* OF)
{
	BIT_HI = BYTE_TO_INT(OF) << 8;
	BIT_LO = BYTE_TO_INT(OF) = 0 << 7;
	return BIT_SUM;
}

#endif


int main(int argc, char** argv)
{
	COMPUTE_CHECKSUM();
	BYTE_TO_INT();
	WORD_TO_INT();
	return 0;
}
